version: '3'
services:
  backend:
    build:
      context: ./backend
      # dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - node_env=prod

  frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
    ports:
      - 8080:5173
    environment:
      - VITE_API_BASE_URL=backend:3000
    depends_on:
      - backend


  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: